#ifndef APROKSYMACJA_ILOSCPUNKTOWORAZWSKAZNIKI_H
#define APROKSYMACJA_ILOSCPUNKTOWORAZWSKAZNIKI_H

typedef double(*wskaznik)(double, int);
const int iloscPunktow = 100;

#endif //APROKSYMACJA_ILOSCPUNKTOWORAZWSKAZNIKI_H
