

#ifndef METODAELIMINACJIGAUSSA_WARUNKINARODZAJMACIERZY_H
#define METODAELIMINACJIGAUSSA_WARUNKINARODZAJMACIERZY_H

int checkIfNotAllNumbersInRowAreZeros(double **matrix, int n, double *x);

#endif //METODAELIMINACJIGAUSSA_WARUNKINARODZAJMACIERZY_H
